# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: ls -l
    - run: npm ci
    - run: npm run build --if-present   
    - run: echo Despues de compilar proyecto!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    - run: ls -l scripts
    - run: ls -l
    - run: cp -r scripts build
    - run: ls -l build/scripts
    - run: cp appspec.yml build/
    - run: cd build && zip -r cicd.zip *    
    - run: echo Despues de comprimir
    - run: ls -l
    - name: Install AWS CLI
      run: |
          sudo apt-get install -y python3-pip
          pip3 install awscli
    - name: Copy to S3
      run: |
          aws s3 cp build/cicd.zip s3://cicdgithub/
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
